version: '{build}'

environment:
  AUTH_TOKEN:
    secure: EQ9miMjfX/QAoBvgc6D+JLmHatLyxOEKZ/uo68QijxWW5Gp4MzB/pOH9+u2GlDVO

build_script:
  - git config --global user.name "Smile-DK"
  - git config --global user.email "2236141431@qq.com"
  - git checkout master
  - git clone https://github.com/purerosefallen/ygopro-222DIY
  - cd ygopro-222DIY

  - cp -rf ../expansions/script expansions

  - git add . -A
  - git commit -m "Auto Push by Miyuki"

  - git checkout data
  - cp -rf ../expansions/pics expansions
  - cp -rf ../expansions/script expansions
  - cp -rf ../sound .
  - cd update
  - update.exe -ci
  - cd ..

  - git add . -A
  - git commit -m "Auto Push by Miyuki"
  - git push https://%AUTH_TOKEN%@github.com/purerosefallen/ygopro-222DIY master data
  - cd ..

test: off

branches:
  only:
    - master
